package one.lindegaard.CustomItemsLib.rewards;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map.Entry;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.metadata.FixedMetadataValue;
import org.bukkit.plugin.Plugin;

import one.lindegaard.CustomItemsLib.Core;
import one.lindegaard.CustomItemsLib.Tools;
import one.lindegaard.CustomItemsLib.materials.Materials;

public class RewardBlockManager {

	private Plugin plugin;
	private File file;
	private YamlConfiguration config = new YamlConfiguration();
	private boolean dataChanged = false;

	private HashMap<Integer, RewardBlock> rewardBlocks = new HashMap<Integer, RewardBlock>();

	public RewardBlockManager(Plugin plugin) {
		this.plugin = plugin;
		file = new File(plugin.getDataFolder().getParent(), "BagOfGold/rewards.yml");
		load();
		Bukkit.getPluginManager().registerEvents(new CoreRewardListeners(plugin), plugin);
	}

	/**
	 * Remove the Reward block from the world and clean up in saved rewards.
	 * 
	 * @param block
	 */
	public void removeReward(Block block) {
		if (Reward.isReward(block)) {
			Reward reward = Reward.getReward(block);
			Core.getMessages().debug("Removing block from world (id=%s)", reward.getUniqueID());
			block.getDrops().clear();
			block.setType(Material.AIR);
			block.removeMetadata(Reward.MH_REWARD_DATA_NEW, plugin);
			if (rewardBlocks.containsKey(reward.getUniqueID())) {

			}
			dataChanged = true;
		}
	}

	public void addReward(Block block, Reward reward) {
		block.setMetadata(Reward.MH_REWARD_DATA_NEW, new FixedMetadataValue(plugin, reward));
		rewardBlocks.put(reward.getUniqueID(), new RewardBlock(block.getLocation(), reward));
		dataChanged = true;
	}

	public int getNextID() {
		int max = 0;
		for (int n : rewardBlocks.keySet())
			max = Math.max(max, n);
		return max + 1;
	}

	private boolean isGenerated(Location location) {
		return location != null
				&& location.getWorld().isChunkGenerated(location.getChunk().getX(), location.getChunk().getZ());
	}

	public void save() {
		int n = 0;
		if (dataChanged) {
			try {
				config.options()
						.setHeader(Arrays.asList(new String[] { "This is the rewards placed as blocks.",
								"Do not edit this file manually!!!",
								"If you remove a section the reward will loose its value on next server restart." }));
				for (Iterator<Entry<Integer, RewardBlock>> itr = rewardBlocks.entrySet().iterator(); itr.hasNext();) {
					Entry<Integer, RewardBlock> id = itr.next();
					Location location = id.getValue().getLocation();
					Reward reward = id.getValue().getReward();
					if (isGenerated(location)) {
						if (Materials.isSkull(location.getBlock().getType())) {
							ConfigurationSection section = config.createSection(id.getKey().toString());
							section.set("location", location.clone());
							reward.save(section);
							config.save(file);
							n++;
						} else {
							config.set(id.getKey().toString(), null);
							itr.remove();
						}
					} else {
						Core.getMessages().debug(
								"This location is not generated (%s,%s,%s,%s) (Maybe the world has been regenerated?) - deleting reward block",
								location.getWorld().getName(), location.getBlockX(), location.getY(), location.getZ());
						config.set(id.getKey().toString(), null);
						itr.remove();
					}
				}
				if (n > 0) {
					Core.getMessages().debug("Saved %s rewards to disk", n);
					dataChanged = false;
				}
			} catch (IOException e) {
				e.printStackTrace();
			}
		} // else
			// Core.getMessages().debug("No rewards was placed or removed. Nothing to write
			// to rewards.yml");
	}

	public void load() {
		int n = 0;
		int deleted = 0;
		try {
			if (file.exists())
				config.load(file);
		} catch (IllegalArgumentException | InvalidConfigurationException e) {
			Bukkit.getConsoleSender().sendMessage(Core.PREFIX + ChatColor.RED
					+ " The rewards.yml file contain broken rewards. They will be deleted. ");
		} catch (IOException e) {
			e.printStackTrace();
		}

		for (String key : config.getKeys(false)) {
			ConfigurationSection section = config.getConfigurationSection(key);
			Reward reward = new Reward();
			try {
				reward.read(section);
			} catch (InvalidConfigurationException e) {
				Bukkit.getConsoleSender()
						.sendMessage(Core.PREFIX + ChatColor.RED + " Could not load reward no. " + key + ".");
			}

			Location location = (Location) section.get("location");
			for (RewardBlock rb : rewardBlocks.values()) {
				if (rb.equals(new RewardBlock(location, reward)))
					continue;
			}
			if (isGenerated(location) && Materials.isSkull(location.getBlock().getType())) {
				n++;
				reward.setUniqueID(n);
				location.getBlock().setMetadata(Reward.MH_REWARD_DATA_NEW,
						new FixedMetadataValue(plugin, new Reward(reward)));
				rewardBlocks.put(n, new RewardBlock(location, reward));
				if (Tools.isUUID(key)) {
					deleted++;
					config.set(key, null);
				}
			} else {
				// This block is not a PLAYER_HEAD, delete the section.
				deleted++;
				config.set(key, null);
			}
		}

		try {

			if (deleted > 0) {
				Core.getMessages().debug("Deleted %s rewards from the rewards.yml file", deleted);
				File file_copy = new File(plugin.getDataFolder(), "rewards.yml.old");
				Files.copy(file.toPath(), file_copy.toPath(), StandardCopyOption.COPY_ATTRIBUTES,
						StandardCopyOption.REPLACE_EXISTING);
				config.save(file);
			}
			if (n > 0) {
				Core.getMessages().debug("Loaded %s rewards from the BagOfGold/rewards.yml file", n);
			}

		} catch (IOException e) {
			e.printStackTrace();
		}

		// Import files from MobHunting to BagOfGold/rewards.yml
		File file2 = new File(plugin.getDataFolder().getParent(), "MobHunting/rewards.yml");
		if (file2.exists()) {
			Core.getMessages().debug("Loading rewards from MobHunting first time.");
			migrateRewardsFromMobHunting(file2);
		}
	}

	private void migrateRewardsFromMobHunting(File file) {
		if (!file.exists())
			return;

		YamlConfiguration mobhunting_rewards = new YamlConfiguration();
		int n = 0;

		try {
			mobhunting_rewards.load(file);
		} catch (IOException | InvalidConfigurationException e1) {
			e1.printStackTrace();
		}

		try {
			for (String key : mobhunting_rewards.getKeys(false)) {
				ConfigurationSection section = mobhunting_rewards.getConfigurationSection(key);
				Reward reward = new Reward();
				reward.read(section);
				Location location = (Location) section.get("location");
				for (RewardBlock rb : rewardBlocks.values()) {
					if (rb.equals(new RewardBlock(location, reward)))
						continue;
				}
				if (location != null && Materials.isSkull(location.getBlock().getType())) {
					n++;
					reward.setUniqueID(n);
					location.getBlock().setMetadata(Reward.MH_REWARD_DATA_NEW,
							new FixedMetadataValue(plugin, new Reward(reward)));
					rewardBlocks.put(n, new RewardBlock(location, reward));
				}
			}
		} catch (InvalidConfigurationException e) {
			e.printStackTrace();
		}
		if (n > 0) {
			Core.getMessages().debug("Loaded %s rewards from the MobHunting/rewards.yml file." + ChatColor.RED
					+ " Renaming MobHunting/rewards.yml to MobHunting/rewards.yml.old", n);
			file.renameTo(new File(file.getPath() + ".old"));
			dataChanged = true;
		}

	}

}
